### ISSUE TITLE
pandacan doesn't work: USBErrorBusy: LIBUSB_ERROR_BUSY on python 2 and ModuleNotFoundError: No module named 'dfu' on python 3

### ISSUE THREAD

**Issue by shurikrulik** [commaai/panda#154]
python 2:

Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from panda import Panda
>>> Panda.list()
[u'480031000551363338383037']
>>> panda = Panda()
opening device 480031000551363338383037 0xddcc
exception LIBUSB_ERROR_BUSY [-6]
Traceback (most recent call last):
  File "/home/burningman/.local/lib/python2.7/site-packages/panda/__init__.py", line 163, in connect
    self._handle.claimInterface(0)
  File "/home/burningman/.local/lib/python2.7/site-packages/usb1/__init__.py", line 1300, in claimInterface
    libusb1.libusb_claim_interface(self.__handle, interface),
  File "/home/burningman/.local/lib/python2.7/site-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/home/burningman/.local/lib/python2.7/site-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
USBErrorBusy: LIBUSB_ERROR_BUSY [-6]
connected
>>> panda.can_recv()
CAN: BAD RECV, RETRYING
CAN: BAD RECV, RETRYING
CAN: BAD RECV, RETRYING
CAN: BAD RECV, RETRYING
CAN: BAD RECV, RETRYING

python 3:

Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from panda import Panda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/burningman/.local/lib/python3.6/site-packages/panda/__init__.py", line 11, in <module>
    from dfu import PandaDFU
ModuleNotFoundError: No module named 'dfu'

Drivers installed, 11-panda.rules edited, panda connected through USB cable and led indicates ready to work status. What is the problem ?

**Comment by shreyansh073** [comment]
The problem lies in the script panda/python/__init__.py at line 193.
`self._handle.claimInterface(0)` Here it throws libusbbusy error because some other driver has claimed the usb already. Thus a common practise is to detach all kernels before claiming the usb for synchronous I/O. Just add `self._handle.setAutoDetachKernelDriver(True)` after `self._handle = device.open()` and this should solve the problem.
