### ISSUE TITLE
running panda scons fills up user storage

### ISSUE THREAD

**Issue by dzid26** [commaai/panda#1850]
```
df
cd panda
scons
df
scons 
df
scons
df
scons
```

I was changing files in between scons.  

tmp and home free space kept decreasing to the point I couldn't do anything. Reboot helps.  I was able to repeat this four times with a combination of scons and flash.py.
Maybe cppcheck does it? - just a guess. 

Reboot helps. 

```
df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       10255636 4431908   5283056  46% /
devtmpfs         1725472       0   1725472   0% /dev
tmpfs            1831456       0   1831456   0% /dev/shm
tmpfs             366292   22464    343828   7% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs            1831456       0   1831456   0% /sys/fs/cgroup
tmpfs             131072   10800    120272   9% /var
tmpfs             153600     140    153460   1% /tmp
/dev/sda2          27632      28     25316   1% /persist
/dev/sda10         11760      24     10596   1% /systemrw
/dev/sda12      91788820 7235728  79847412   9% /data
/dev/sda11        110576      36    101368   1% /cache
/dev/sde26         28144   20048      7444  73% /dsp
/dev/sde4         122816   43984     78832  36% /firmware
overlay           153600     140    153460   1% /home
tmpfs             366288       0    366288   0% /run/user/1000
```
```
df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       10255636 4431908   5283056  46% /
devtmpfs         1725472       0   1725472   0% /dev
tmpfs            1831456       0   1831456   0% /dev/shm
tmpfs             366292   22464    343828   7% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs            1831456       0   1831456   0% /sys/fs/cgroup
tmpfs             131072   10800    120272   9% /var
tmpfs             153600   60168     93432  40% /tmp
/dev/sda2          27632      28     25316   1% /persist
/dev/sda10         11760      24     10596   1% /systemrw
/dev/sda12      91788820 7235916  79847224   9% /data
/dev/sda11        110576      36    101368   1% /cache
/dev/sde26         28144   20048      7444  73% /dsp
/dev/sde4         122816   43984     78832  36% /firmware
overlay           153600   60168     93432  40% /home
tmpfs             366288       0    366288   0% /run/user/1000
```
```
df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       10255636 4431908   5283056  46% /
devtmpfs         1725472       0   1725472   0% /dev
tmpfs            1831456       0   1831456   0% /dev/shm
tmpfs             366292   22464    343828   7% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs            1831456       0   1831456   0% /sys/fs/cgroup
tmpfs             131072   10800    120272   9% /var
tmpfs             153600   77660     75940  51% /tmp
/dev/sda2          27632      28     25316   1% /persist
/dev/sda10         11760      24     10596   1% /systemrw
/dev/sda12      91788820 7235944  79847196   9% /data
/dev/sda11        110576      36    101368   1% /cache
/dev/sde26         28144   20048      7444  73% /dsp
/dev/sde4         122816   43984     78832  36% /firmware
overlay           153600   77660     75940  51% /home
tmpfs             366288       0    366288   0% /run/user/1000
```
```
 df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       10255636 4431908   5283056  46% /
devtmpfs         1725472       0   1725472   0% /dev
tmpfs            1831456       0   1831456   0% /dev/shm
tmpfs             366292   22464    343828   7% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs            1831456       0   1831456   0% /sys/fs/cgroup
tmpfs             131072   10800    120272   9% /var
tmpfs             153600  110928     42672  73% /tmp
/dev/sda2          27632      28     25316   1% /persist
/dev/sda10         11760      24     10596   1% /systemrw
/dev/sda12      91788820 7236000  79847140   9% /data
/dev/sda11        110576      36    101368   1% /cache
/dev/sde26         28144   20048      7444  73% /dsp
/dev/sde4         122816   43984     78832  36% /firmware
overlay           153600  110928     42672  73% /home
tmpfs             366288       0    366288   0% /run/user/1000
```
```
 df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       10255636 4431908   5283056  46% /
devtmpfs         1725472       0   1725472   0% /dev
tmpfs            1831456       0   1831456   0% /dev/shm
tmpfs             366292   22464    343828   7% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs            1831456       0   1831456   0% /sys/fs/cgroup
tmpfs             131072   10800    120272   9% /var
tmpfs             153600  110928     42672  73% /tmp
/dev/sda2          27632      28     25316   1% /persist
/dev/sda10         11760      24     10596   1% /systemrw
/dev/sda12      91788820 7236000  79847140   9% /data
/dev/sda11        110576      36    101368   1% /cache
/dev/sde26         28144   20048      7444  73% /dsp
/dev/sde4         122816   43984     78832  36% /firmware
overlay           153600  110928     42672  73% /home
tmpfs             366288       0    366288   0% /run/user/1000
```
```
df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       10255636 4431908   5283056  46% /
devtmpfs         1725472       0   1725472   0% /dev
tmpfs            1831456       0   1831456   0% /dev/shm
tmpfs             366292   22468    343824   7% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs            1831456       0   1831456   0% /sys/fs/cgroup
tmpfs             131072   11688    119384   9% /var
tmpfs             153600  137060     16540  90% /tmp
/dev/sda2          27632      28     25316   1% /persist
/dev/sda10         11760      24     10596   1% /systemrw
/dev/sda12      91788820 7236164  79846976   9% /data
/dev/sda11        110576      36    101368   1% /cache
/dev/sde26         28144   20048      7444  73% /dsp
/dev/sde4         122816   43984     78832  36% /firmware
overlay           153600  137060     16540  90% /home
tmpfs             366288       0    366288   0% /run/user/1000
```

```
df
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       10255636 4431908   5283056  46% /
devtmpfs         1725472       0   1725472   0% /dev
tmpfs            1831456       0   1831456   0% /dev/shm
tmpfs             366292   17884    348408   5% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs            1831456       0   1831456   0% /sys/fs/cgroup
tmpfs             153600  153600         0 100% /tmp
tmpfs             131072   10812    120260   9% /var
/dev/sda2          27632      28     25316   1% /persist
/dev/sda12      91788820 8015248  79067892  10% /data
/dev/sda10         11760      24     10596   1% /systemrw
/dev/sda11        110576      36    101368   1% /cache
/dev/sde26         28144   20048      7444  73% /dsp
/dev/sde4         122816   43984     78832  36% /firmware
overlay           153600  153600         0 100% /home
tmpfs             366288       0    366288   0% /run/user/1000
```

```
/usr/local/pyenv/versions/3.11.4/bin/python /data/openpilot/panda/tests/health_test.py
Traceback (most recent call last):
  File "/data/openpilot/panda/tests/health_test.py", line 3, in <module>
    from panda import Panda
  File "/data/pythonpath/panda/__init__.py", line 1, in <module>
    from .python.constants import McuType, BASEDIR, FW_PATH, USBPACKET_MAX_SIZE  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/pythonpath/panda/python/__init__.py", line 5, in <module>
    import usb1
  File "/usr/local/pyenv/versions/3.11.4/lib/python3.11/site-packages/usb1/__init__.py", line 765, in <module>
    USBTransfer._USBTransfer__ctypesCallbackWrapper = libusb1.libusb_transfer_cb_fn_p(
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
MemoryError
```

**Comment by dzid26** [comment]
I will keep investigating.  Maybe it is caused by vscode remote
