### ISSUE TITLE
getting an error No module named 'request'

### ISSUE THREAD

**Issue by hedgehogdrfrink** [commaai/panda#2006]
getting an error when trying to setup a connection with comma 3x to pull files off of it,

./som_debug.sh 
Traceback (most recent call last):
  File "/home/user/Downloads/openpilotv1/panda/tests/./debug_console.py", line 9, in <module>
    from panda import Panda
  File "/home/user/Downloads/openpilotv1/venv/lib/python3.11/site-packages/panda/__init__.py", line 1, in <module>
    from request import PandaRequest
ModuleNotFoundError: No module named 'request'

Followed along with the readme to set it up, not sure what I'm doing wrong at this point.

**Comment by adeebshihadeh** [comment]
You have this installed: https://pypi.org/project/panda/. It's not using this panda library.

**Comment by hedgehogdrfrink** [comment]
Thank you, fixed the issue
