### ISSUE TITLE
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3], no pandas found

### ISSUE THREAD

**Issue by hedgehogdrfrink** [commaai/panda#2007]
getting the following error below when trying to connect to comma 3x,
not sure how to debug and didn't see any open or closed issues with the same error

```
$./som_debug.sh
error connecting to panda
Traceback (most recent call last):
  File "/home/user/Downloads/openpilotv1/venv/lib/python3.11/site-packages/pandacan-0.0.10-py3.11.egg/panda/__init__.py", line 406, in usb_list
    serial = device.getSerialNumber()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/openpilotv1/venv/lib/python3.11/site-packages/usb1/__init__.py", line 2019, in getSerialNumber
    return self.open().getSerialNumber()
           ^^^^^^^^^^^
  File "/home/user/Downloads/openpilotv1/venv/lib/python3.11/site-packages/usb1/__init__.py", line 2055, in open
    mayRaiseUSBError(libusb1.libusb_open(self.device_p, byref(handle)))
  File "/home/user/Downloads/openpilotv1/venv/lib/python3.11/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/home/user/Downloads/openpilotv1/venv/lib/python3.11/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
no pandas found
```

**Comment by adeebshihadeh** [comment]
Closing as this isn't a bug - check out our [Discord](https://discord.comma.ai) instead for help with this.
