### ISSUE TITLE
ImportError: No module named panda

### ISSUE THREAD

**Issue by progen** [commaai/panda#275]
**Installed pandacan using:** 
$pip install pandacan

**And then ran** 
$python
>>>from panda import Panda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named panda
--------
**tried python3 instead**
$python3
>>>from panda import Panda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/panda/__init__.py", line 7, in <module>
    import usb1
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/usb1/__init__.py", line 61, in <module>
    from . import libusb1
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/usb1/libusb1.py", line 199, in <module>
    libusb = _loadLibrary()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/usb1/libusb1.py", line 173, in _loadLibrary
    return dll_loader('libusb-1.0' + suffix, **loader_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libusb-1.0.dylib, 6): image not found

**Comment by progen** [comment]
Seems that my pip was pointed to the wrong python version.
Re-installed Python 2.7 and the ImportError was FIXED.
As for the libusb error, on my mac i installed libusb manually using homebrew instead of pip installing the requirements and the OSError was Fixed.
