### ISSUE TITLE
UDS failure, exception during exception.

### ISSUE THREAD

**Issue by rdamron** [commaai/panda#312]
Receiving the following error when running eps read example on a 2018 honda accord.
Updated pandacan with `pip install .` 
Shows as pandacan-0.0.9
plugging into Comma Black

`➜  python git:(master) ✗ ./eps_read_software_ids.py
opening device 290055000e51373038323837 0xddcc
connected
tester present ...
ISO-TP: REQUEST - b'3e00'
ISO-TP: TX - single frame
CAN-TX: 0x18da30f1 - b'023e000000000000'
ISO-TP: RESPONSE - b''
Traceback (most recent call last):
  File "/Users/dandy/Projects/panda/python/uds.py", line 309, in recv
    self._isotp_rx_next()
  File "/Users/dandy/Projects/panda/python/uds.py", line 318, in _isotp_rx_next
    rx_data = self.can_rx_queue.get(block=True, timeout=self.timeout)
  File "/Users/dandy/.pyenv/versions/3.7.3/lib/python3.7/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./eps_read_software_ids.py", line 11, in <module>
    uds_client.tester_present()
  File "/Users/dandy/Projects/panda/python/uds.py", line 510, in tester_present
    self._uds_request(SERVICE_TYPE.TESTER_PRESENT, subfunction=0x00)
  File "/Users/dandy/Projects/panda/python/uds.py", line 448, in _uds_request
    resp = isotp_msg.recv()
  File "/Users/dandy/Projects/panda/python/uds.py", line 313, in recv
    raise MessageTimeoutError("timeout waiting for response")
uds.MessageTimeoutError: timeout waiting for response`

**Comment by rdamron** [comment]
Selected the wrong bus.
