### ISSUE TITLE
updating panda over USB fails

### ISSUE THREAD

**Issue by gregjhogan** [commaai/panda#51]
From a linux machine (instructions from panda/UPDATING.md)

```
$ PYTHONPATH="" sudo python -c "import panda; panda.flash_release()"
Using panda with serial 4d003b000651363038363036
Fetching latest firmware from github.com/commaai/panda-artifacts
Fetching firmware from https://github.com/commaai/panda-artifacts/raw/master/panda-v1.0.1-11d45090-RELEASE.zip
File Name                                             Modified             Size
bootstub.panda.bin                             2017-10-15 17:12:00        12348
panda.bin                                      2017-10-15 17:12:00        19260
user1.bin                                      2017-10-15 17:12:02       246980
user2.bin                                      2017-10-15 17:12:02       246980
boot_v1.5.bin                                  2016-05-20 16:53:08         3232
version                                        2017-10-15 17:12:02           23
0. Preparing to flash v1.0.1-11d45090-RELEASE
1. Entering DFU mode
opening device 4d003b000651363038363036 0xddcc
connected
LIBUSB_ERROR_PIPE [-9]
2. Programming bootstub
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "panda/panda/flash_release.py", line 57, in flash_release
    dfu = PandaDFU(PandaDFU.st_serial_to_dfu_serial(st_serial))
  File "panda/panda/dfu.py", line 28, in __init__
    raise Exception("failed to open "+dfu_serial)
Exception: failed to open 366B368F3036
```

ultimately I did get it updated by using panda/release/ota_release.sh but even that threw a strange "wrong!" message

```
$ ./release/ota_release.sh panda-v1.0.1-11d45090-RELEASE.zip
Archive:  panda-v1.0.1-11d45090-RELEASE.zip
  inflating: /tmp/panda_firmware/bootstub.panda.bin
  inflating: /tmp/panda_firmware/panda.bin
  inflating: /tmp/panda_firmware/user1.bin
  inflating: /tmp/panda_firmware/user2.bin
  inflating: /tmp/panda_firmware/boot_v1.5.bin
 extracting: /tmp/panda_firmware/version
<pre>This is your comma.ai panda<br/><br/>It's open source. Find the code <a href="https://github.com/commaai/panda">here</a><br/>Designed to work with our dashcam, <a href="http://chffr.comma.ai">chffr</a><br/><br/>ssid: panda-07f39d76c38bc541<br/><br/>st version:     v1.0.1-11d45090-RELEASE<br/>esp version:    v1.0.1-11d45090-RELEASE<br/>esp flash file: user2.binflashing user1
wrong!
flashing user2
success!
waiting 10s for reboot
flashing st
success!
<pre>This is your comma.ai panda<br/><br/>It's open source. Find the code <a href="https://github.com/commaai/panda">here</a><br/>Designed to work with our dashcam, <a href="http://chffr.comma.ai">chffr</a><br/><br/>ssid: panda-07f39d76c38bc541<br/><br/>st version:     v1.0.1-11d45090-RELEASE<br/>esp version:    v1.0.1-11d45090-RELEASE<br/>esp flash file: user1.bindone
```

**Comment by nsamala** [comment]
I had a similar issue on a Mac.

Run `make recover` from the `board directory` of your local copy of this repo. This should fix it. You can then re-rerun the upgrade and it should work without errors.
