### ISSUE TITLE
flash_release() issue #596 not fixed (but was closed)

### ISSUE THREAD

**Issue by nebukadnezar** [commaai/panda#597]
Still not working. Reinstalled a clean ubuntu 16 VM and encountered a sleuth of problems both with make, make recover from inside the board directory. Since this is about the flash_release() failing, I'm posting only the errors happening using that flash attempt:

```
(panda-venv) balt@ubuntu:~$ python -c "import panda; panda.flash_release()"
Fetching latest firmware from github.com/commaai/panda-artifacts
Fetching firmware from https://github.com/commaai/panda-artifacts/raw/master/panda-v1.7.3-DEV-d034f3e9-RELEASE.zip
File Name                                             Modified             Size
bootstub.panda.bin                             2020-02-05 11:47:44        13348
panda.bin                                      2020-02-05 11:47:44        34088
user1.bin                                      2020-02-05 11:47:46       248212
user2.bin                                      2020-02-05 11:47:46       248212
boot_v1.5.bin                                  2016-05-20 16:53:08         3232
version                                        2020-02-05 11:47:48           27
0. Preparing to flash v1.7.3-DEV-d034f3e9-RELEASE
1. Entering DFU mode
opening device 340059000e51363339383037 0xddcc
connected
reconnecting is taking 1 seconds...
reconnecting is taking 2 seconds...
reconnecting is taking 3 seconds...
opening device 340059000e51363339383037 0xddee
connected
2. Programming bootstub
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/balt/panda/python/flash_release.py", line 52, in flash_release
    dfu = PandaDFU(PandaDFU.st_serial_to_dfu_serial(st_serial))
  File "/home/balt/panda/python/dfu.py", line 27, in __init__
    raise Exception("failed to open " + dfu_serial if dfu_serial is not None else "DFU device")
Exception: DFU device
```
The st_serial in line 52 of flash_release is None. I tried calling with the devices serial number, resulting in a failed to open message:

```
python -c "import panda; panda.flash_release(st_serial=\"340059000e51363339383037\")"
Using panda with serial 340059000e51363339383037
Fetching latest firmware from github.com/commaai/panda-artifacts
Fetching firmware from https://github.com/commaai/panda-artifacts/raw/master/panda-v1.7.3-DEV-d034f3e9-RELEASE.zip
File Name                                             Modified             Size
bootstub.panda.bin                             2020-02-05 11:47:44        13348
panda.bin                                      2020-02-05 11:47:44        34088
user1.bin                                      2020-02-05 11:47:46       248212
user2.bin                                      2020-02-05 11:47:46       248212
boot_v1.5.bin                                  2016-05-20 16:53:08         3232
version                                        2020-02-05 11:47:48           27
0. Preparing to flash v1.7.3-DEV-d034f3e9-RELEASE
1. Entering DFU mode
opening device 340059000e51363339383037 0xddcc
connected
reconnecting is taking 1 seconds...
reconnecting is taking 2 seconds...
reconnecting is taking 3 seconds...
opening device 340059000e51363339383037 0xddee
connected
2. Programming bootstub
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/balt/panda/python/flash_release.py", line 52, in flash_release
    dfu = PandaDFU(PandaDFU.st_serial_to_dfu_serial(st_serial))
  File "/home/balt/panda/python/dfu.py", line 27, in __init__
    raise Exception("failed to open " + dfu_serial if dfu_serial is not None else "DFU device")
Exception: failed to open 378938763336
```

**Comment by robbederks** [comment]
Going to close this issue, you can re-open the first issue when it is not resolved. Added a comment to the other issue.
